export const mvgrList = [
  "BAA - Biosciences Merck",
  "BAB - Bioscience BG",
  "BAC - Bioscience BG - Deemed Service",
  "BAD - Bioscience BG - Service",
  "JAA - ISD",
  "LAA - PCS",
  "LAC - Pigments - Cosmetics",
  "LAD - Fine Chemicals - Technical Grade",
  "LAE - Execepients",
  "LAF - Patinals",
  "LAG - Guaiazulene",
  "LAH - Other Pharmaceutical Ingredients",
  "LAI - Industrial Pigments",
  "LAJ - Process Separation Products",
  "LAK - Ionic Liquids",
  "LAM - Pharma Bulk LSP",
  "LAN - CHN - Nutrition",
  "LAP - Pigments  Automotives",
  "LAR - Local Pharma Products",
  "LAS - Protection Products",
  "LAU - Beauty Products",
  "LAV - Vitamin E & Derivatives",
  "LAW - Vitamin Premixes",
  "LAX - Third Party PCS",
  "LAY - Oxynex   ST",
  "LDA - PAA Mica IND Standard Range",
  "LDB - PBA Mica COA ST",
  "LDC - PBC Xirallic COA ST",
  "LDD - PBD Mica COA Pyrisma ST",
  "LDE - PAE Glass Flakes IND",
  "LDF - PFC Mica Iriotec 7000 (Conductivity)",
  "LDG - PAG Silica Flakes IND",
  "LDH - PBB Silica Flakes COA ST",
  "LDJ - PFJ Others Iriotec 8000 (Laser Marking)",
  "LDL - PAL BiOCl IND",
  "LDM - PAM Mica COA",
  "LDN - POM MeOxAL COA ST",
  "LDO - POB BiOCl COA",
  "LDP - PAP Synthetic Mica IND",
  "LDQ - PED Mica Iriotec 8000 (Laser Marking)",
  "LDR - PSM Synthetic Mica COS",
  "LDT - PAU Mica IND EP",
  "LDU - PEJ Mica IND Taizhu",
  "LDX - PYG Mica IND",
  "LF1 - PYR Functional Additives",
  "LFA - PCA Mica COS",
  "LFB - PCB Glass Flakes COS",
  "LFC - PCC Silica Flakes COS",
  "LFD - PDB Organic UV Filters",
  "LFE - PEO Others Security",
  "LFF - PEF BiOCl Filler",
  "LFG - PDG Synthetic Mica Filler",
  "LFH - PDH SiO2 Filler",
  "LFJ - PDJ Cosmetic Customized Ingredients",
  "LFK - PDK Antioxidant",
  "LFL - PDL Inorganic UV Filters (Eusolex)",
  "LFM - PEG Mica Filler",
  "LFN - PAN Skin Care Actives",
  "LFO - PAO Pigmentation Control",
  "LFP - PAQAluminaCOS",
  "LFQ - PAR BiOCl COS",
  "LFR - PEH Other Substrates Filler",
  "LFS - SECURALICGREEN-RED1KG",
  "LFT - PDA Thioglycolic Acid and its",
  "LFU - PDE Third Party Prod. COS",
  "LFV - PDO Others",
  "LFW - PFH Mica Iriotec 9000 (Heat management)",
  "LFX - PIR Insect Repellent",
  "LFY - PNI  Natural Ingredients",
  "LFZ - PYF Repellent and Others",
  "RAA - Emil - Small Packs",
  "RAB - Emil - Bulk Packs",
  "RAC - MDA - Reagents Small Packs",
  "RAD - Dr. ERH",
  "RAE - MDA - Reagents Bulk Packs",
  "RAF - Liquid Handling  Products",
  "RAG - Hermle",
  "RAH - Filteration Products",
  "RAJ - Denver Products",
  "RAK - Microscopy Products",
  "RAL - Prolabo /GFL  Products",
  "RBC - Glassware",
  "RBE - Novabiochem Reagents",
  "SAA - Emil Lichrosolv Solvents",
  "SAB - MDA Hipersolv Solvents",
  "SAC - MDA  Columns",
  "SAD - Local  Columns",
  "SAE - Chrom - Plates",
  "SAF - Chrom - Misc.",
  "SAG - Chrom - SPE local",
  "SAH - Chrom - USP Ref. Std.",
  "SAJ - Chrom - Hamilton Products",
  "SAK - Chrom - Ch. Tools",
  "SAL - Chrom - Dr Maisch Columns",
  "SAM - Chrom - LAPHA Pack",
  "SAN - Chrom - Instruments",
  "SAP - Chrom - Pick Lab",
  "SAQ - Chrom - Elga",
  "SAS - WnFA - EMD Kits",
  "SAT - WnFA - Local Kits",
  "SAU - WnFA - EMD Intruments",
  "SAV - WnFA - Eutech Products",
  "SAW - WnFA  -Shott",
  "SAX - WnFA - B & S",
  "SAY - WnFA - Thermospectronic",
  "SAZ - WnFA - WTW",
  "SBA - Biomonitoring Merck Local",
  "SBB - Biomonitoring Merck Local (BRM)",
  "SBC - Biomonitoring MDA",
  "SBD - Biomonitoring Instruments",
  "SBE - Biomonitoring Rapid Test Kits",
  "SBF - Biomonitoring Hycon",
  "SBG - Biomonitoring Heipha",
  "SDA - CLC - Kits",
  "SDB - CLC- Instruments",
  "SDD - MDA Microscopy",
  "SDE - DoA Cozart ( Drugs of Abuse)",
  "Y01 - BPS Traded",
  "Y02 - BPS-Mfgd",
  "Y03 - BPS-Service",
  "Y14 - LS",
  "Y18 - LW Accessories",
  "Y19 - LW Consumables",
  "Y22 - Biom- Mfgd In Process Testing",
  "Y23 - Biom-Traded Env Monitoring",
  "Y24 - Biom-Traded In Process Testing",
  "Y25 - Biom-Traded Release Testing",
  "Y26 - Bios- ASP Mfgd",
  "Y27 - Bios- ASP Traded",
  "Y29 - Bios-Traded",
  "Y31 - Bios-Traded MCBS",
  "Y33 - Probumin (TD)",
  "Y34 - Bio Science",
  "Y35 - Bio Process",
  "Y36 - Biom- Service",
  "Y37 - LW Hardware",
  "Y38 - PCS-Traded",
  "Y40 - LW Service",
].map((d) => {
  return {
    label: d,
    value: d,
  };
});